sudo: required
services:
  - docker

before_install:
    - docker build -t elzette/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true elzette/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-north-1"
    app: "frontend"
    env: "Frontend-env"
    bucket_name: "elasticbeanstalk-eu-north-1-720050945230"
    bucket_path: "Frontend-env"
    on:
      branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"

